name: Sync m3e-canvas Upstream
permissions:
  contents: write
on:
  schedule:
    - cron: '0 2 * * *' # UTC 每天凌晨2点执行（北京时间上午10点）
  workflow_dispatch: # 支持手动点按钮触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork with upstream
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh repo sync ${{ github.repository }}
